### ISSUE TITLE
Can't Make This Work

### ISSUE THREAD

**Issue by bradennapier** [germanrcuriel/hipchat-client#12]
So I am not sure what specifically is going on here.  Trying to get this working with webpack on amazon aws lambda and it crashes when I try to use it.

It started with these errors:

```
WARNING in ./~/harmony/~/formidable/lib/incoming_form.js
Critical dependencies:
1:43-50 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./~/harmony/~/formidable/lib/incoming_form.js 1:43-50

WARNING in ./~/harmony/~/formidable/lib/incoming_form.js
Critical dependencies:
1:0-14 the request of a dependency is an expression
 @ ./~/harmony/~/formidable/lib/incoming_form.js 1:0-14

WARNING in ./~/harmony/~/formidable/lib/file.js
Critical dependencies:
1:43-50 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./~/harmony/~/formidable/lib/file.js 1:43-50

WARNING in ./~/harmony/~/formidable/lib/file.js
Critical dependencies:
1:0-14 the request of a dependency is an expression
 @ ./~/harmony/~/formidable/lib/file.js 1:0-14

WARNING in ./~/harmony/~/formidable/lib/querystring_parser.js
Critical dependencies:
1:43-50 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./~/harmony/~/formidable/lib/querystring_parser.js 1:43-50

WARNING in ./~/harmony/~/formidable/lib/querystring_parser.js
Critical dependencies:
1:0-14 the request of a dependency is an expression
 @ ./~/harmony/~/formidable/lib/querystring_parser.js 1:0-14
```

at which point it would appear that webpack needed the gently plugin:

```
new webpack.DefinePlugin({ "global.GENTLY": false })
```

this just results now in crashing on startup

```
module initialization error: Error
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Mime.load (/var/task/testFunction.js:108807:21)
    at Object.<anonymous> (/var/task/testFunction.js:108843:7)
    at Object.module.exports.async (/var/task/testFunction.js:108869:31)
    at __webpack_require__ (/var/task/testFunction.js:21:30)
    at Object.<anonymous> (/var/task/testFunction.js:108129:13)
    at __webpack_require__ (/var/task/testFunction.js:21:30)
    at Object.<anonymous> (/var/task/testFunction.js:105566:17)
    at __webpack_require__ (/var/task/testFunction.js:21:30)
    at Object.<anonymous> (/var/task/testFunction.js:105426:14)
    at Object.<anonymous> (/var/task/testFunction.js:105552:5)
    at __webpack_require__ (/var/task/testFunction.js:21:30)
    at Object.<anonymous> (/var/task/testFunction.js:105290:16)
    at Object.module.exports.indexOf.indexOf.i (/var/task/testFunction.js:105414:5)
    at __webpack_require__ (/var/task/testFunction.js:21:30)
    at Object.<anonymous> (/var/task/testFunction.js:105244:12)
    at Object.<anonymous> (/var/task/testFunction.js:105277:5)
    at __webpack_require__ (/var/task/testFunction.js:21:30)
    at Object.<anonymous> (/var/task/testFunction.js:105218:23)
    at __webpack_require__ (/var/task/testFunction.js:21:30)
```

Would love to get this working!

**Comment by germanrcuriel** [comment]
@bradennapier Thanks for posting the issue.

I really don't understand what's going on here. It doesn't complain about anything related to this package. Can you provide more information?

**Comment by germanrcuriel** [comment]
@bradennapier are you still having that issue?
